### PR TITLE
update search path headers for RN 0.40

### PR DESCRIPTION
**Pull request by smkhalsa**

### CODE REVIEW

**Comment by browniefed** [comment]
Thank you I'll have a full version bump shortly

**Comment by browniefed** [comment]
v5.0 has been published to npm

**Comment by javiercr** [comment]
@smkhalsa I was wondering why did you remove
```
"$(SRCROOT)/../react-native/React/**",
"$(SRCROOT)/node_modules/react-native/React/**",
"$(SRCROOT)/../../../node_modules/react-native/React/**",
```

from the `HEADER_SEARCH_PATHS`? I'm trying to use the project with cocoapods but I'm getting a:
`'React/RCTBridgeModule.h' file not found` error and I suspect is because of this. 

Don't we need those paths in the HEADER_SEARCH_PATH?

**Comment by browniefed** [comment]
I've added them back, as well as added
```
#if __has_include(<React/RCTAssert.h>)
#import <React/RCTBridgeModule.h>
#import <React/RCTUtils.h>
#else // back compatibility for RN version < 0.40
#import "RCTBridgeModule.h"
#import "RCTUtils.h"
#endif

```
To make this backwards compatible

**Comment by browniefed** [comment]
Published as v5.3

**Pull request merged**
