### PR TITLE
intercom sdk to 7.1

### LINKED ISSUE #372: update to intercom v7.1
update to intercom v7.1 so we can use Mobile Carousel

### PR DESCRIPTION
**Pull request by ljcp**
fix https://github.com/tinycreative/react-native-intercom/issues/372

to be noted intercom SDK on iOS needs XCode 11.4+

### CODE REVIEW

**Comment by Olovorr** [comment]
Any news about this PR? :) Our client really wants the new intercom sdk 😅

**Comment by lucasfronza** [comment]
@Olovorr, you can use `"react-native-intercom": "tinycreative/react-native-intercom#04007d2",` in your `package.json` for the moment.

**Review by lucasfronza — APPROVED** [review]

**Comment by aditibarbhai** [comment]
Any word on when this will be released?

**Comment by ljcp** [comment]
you can use this PR

**Comment by aditibarbhai** [comment]
> you can use this PR, we are already using it in our product

Have you had any trouble using this with CocoaPods? I'm getting an error when I do `pod install` with this version ` "react-native-intercom": "tinycreative/react-native-intercom#04007d2"`

**Comment by browniefed** [comment]
Published in react-native-intercom@17.0.0

**Comment by lucasfronza** [comment]
Thanks!

**Pull request merged**
