### PR TITLE
Update Intercom to v6.1.0

### PR DESCRIPTION
**Pull request by rolfb**
Bumping Intercom to v6.1.0 to get the ability to disable message composer which is new in v6.1.0.

### CODE REVIEW

**Comment by pete183** [comment]
Amazing - lets merge this in

**Comment by browniefed** [comment]
v16 released, for changes in version I do major bumps

**Comment by rolfb** [comment]
Thanks! That was fast :)

**Comment by vgm8** [comment]
Can we create a new release for this please?

Thanks in advance!

**Comment by browniefed** [comment]
A new release? It is already release as v16

**Comment by vgm8** [comment]
I can not see it in the release tab: https://github.com/tinycreative/react-native-intercom/releases

**Comment by browniefed** [comment]
I didn't push tags, it's just on NPM

**Comment by vgm8** [comment]
can you push the tags please?

**Pull request merged**
