### PR TITLE
Android integration

### PR DESCRIPTION
**Pull request by atticoos**
This is the initial work for the Android support mentioned in #4

It supports:
- `registerIdentifiedUser`
- `registerUnidentifiedUser`
- `reset`
- `updateUser`
- `logEvent`

### CODE REVIEW

**Comment by ncnlinh** [comment]
@asamiller Hope this can be merged in soon. :dancer:

**Comment by zibs** [comment]
@ajwhite any tips on how to integrate this without the PR being merged yet? appreciate the work!

**Comment by atticoos** [comment]
Sure, you can just `npm install` my branch in the meantime

```
npm install git://github.com/ajwhite/react-native-intercom.git#android-integration --save
```

**Comment by zibs** [comment]
Thanks! Any tips on how to proceed after that heh? I've tried the rnpm linking techniques etc, and following some of the actual intercom steps, but it's not quite panning out. Admittedly I'm not very familiar with Android. Do you have a recommended way for setting this up?

**Comment by atticoos** [comment]
[`npm link` has some known issues](https://github.com/facebook/react-native/issues/637) if that's what you are referring to.

A few steps you'll want to take for the Android configuraiton:

##### `settings.gradle`

Add 

```
include ':react-native-intercom';
project(':react-native-intercom').projectDir = new File(settingsDir, '../node_modules/react-native-intercom/android')
```

##### `app/build.gradle`

Add

```
compile project(':react-native-intercom')
```

##### `MainActivity.java`

Add

``` java
// add import
import com.robinpowered.react.Intercom.IntercomPackage;
import io.intercom.android.sdk.Intercom

// add initialization to onCreate
Intercom.initialize(getApplication(), 'INTERCOM KEY', 'INTERCOM PROJECT');

// add to the `ReactInstacneManager.builder()`
.addPackage(new IntercomPackage())
```

**Comment by zibs** [comment]
heroic! thank you very, very much :zap: -- displayMessageComposer is currently not working, correct?

**Comment by atticoos** [comment]
I don't believe so - if it's not part of this PR, then nope! I haven't had a need for it, so this onky really includes the reporting pieces.

**Comment by zibs** [comment]
Turns out that it already works! One more request, how about configuring the setSecureMode for android? I'll try to get at it, if I can figure it out.
 :D 
 https://docs.intercom.io/configuring-for-your-product-or-site/enabling-secure-mode-on-intercom-for-android

**Comment by browniefed** [comment]
Oh wow this is awesome, thank you.

**Pull request merged**
