### PR TITLE
Add presentArticle method

### PR DESCRIPTION
**Pull request by iagormoraes**
This PR adds the presentArticle method from the intercom SDK

### CODE REVIEW

**Comment by hqarymkevich** [comment]
Could you merge it?

**Comment by iagormoraes** [comment]
> Could you merge it?

for the moment you can use my repo as package to your package.json

**Comment by iagormoraes** [comment]
@browniefed can you take a look to this PR?

**Comment by browniefed** [comment]
react-native-intercom@20.0.0

**Pull request merged**
