### PR TITLE
Add error handling and refactor native modules to use Promises

### PR DESCRIPTION
**Pull request by carlosa54**
Hi, I'm having some problems with android using `react-native-intercom` and decided to add error handling and refactor the native code to use Promises. [IntercomClient.js](https://github.com/tinycreative/react-native-intercom/blob/master/lib/IntercomClient.js) is currently wrapping the Callbacks received from the Native Modules into a chain of promises in javascript, this chain is resolving every promise that it wraps per [this line of code](https://github.com/tinycreative/react-native-intercom/blob/33310a03b582fb6a055e16390cf256f9e326456c/lib/IntercomClient.js#L370) when catching errors.

My use case requires initializing Intercom at a later time (Can't initialize Intercom on the `onCreate()` method as suggested by [Intercom Docs](https://developers.intercom.com/installing-intercom/docs/android-installation#section-step-2-initialize-intercom). This PR adds a new function named `initializeIntercom` that allows later initialization of the Intercom SDK. Although this is not officially supported by Android's Intercom SDK I think it can be useful to some developers.

This PR also drops GCM support and removes `IntercomIntentService.java` currently used for GCM. Google is deprecating GCM on April 11, 2019 and the Intercom Android SDK also removed support since [this release](https://github.com/intercom/intercom-android/releases/tag/5.2.0)

Here's a list of what was done:

* Remove GCM support
* Add error handling that can currently crash the android app
* Add support for later initialization of the Intercom SDK
* Refactor Native Modules to use Promises instead of Callbacks
  * Refactor IntercomClient.js to handle Promises from NativeModules
  * Return errors to the client when rejecting Promises from Native Modules

Let me know what you guys think and if there's any suggestions or improvements to the code.

### CODE REVIEW

**Comment by carlosa54** [comment]
android-example

Here's an example of the current behavior, the is promise being resolved by calling `Intercom.registerIdentifiedUser({}).then(() => alert('Promise resolved'))`. `adb logcat` is running on the right side showing the error being logged.

**Comment by carlosa54** [comment]
@browniefed let me know if there's anything else I can do to get this merged.

**Comment by browniefed** [comment]
Uhm, wow thanks for the rewrite. Do you promise it works and is backwards compatible?
If so yeah, lets merge it.

**Comment by carlosa54** [comment]
@browniefed saw this today, thanks for the reply. Yes I tested the changes on iOS and Android, it's backwards compatible. I'll remove the `initializeIntercom` function to focus this PR only on the refactor. I'll get back to you between today and tomorrow.

**Comment by carlosa54** [comment]
@browniefed added a section on how to configure FCM push notifications for users with existing FCM setups to README, removed the `initializeIntercom` function and did more testing.

Let me know if you have any questions

**Comment by browniefed** [comment]
Awesome! Thanks for this huge effort. I do not use and just depend on community to maintain and fix things so this is greatly appreciated.

Just verifying this is good to go? If it is I'll merge and publish

**Comment by carlosa54** [comment]
> Awesome! Thanks for this huge effort. I do not use and just depend on community to maintain and fix things so this is greatly appreciated.
> 
> Just verifying this is good to go? If it is I'll merge and publish

Yes, everything is good to go. Thanks, there shouldn't be any issues regarding the refactor but I'll be available to help if there's any.

**Comment by browniefed** [comment]
v13 published.

**Comment by levynir** [comment]
Hi, thanks @carlosa54  for the effort and @browniefed for the merge. 

I am thinking that perhaps moving from callbacks promises produces unplanned site-effect of incompatible backward handling of errors. In the old version a fail in the intercom API, if no callback was passed, would result in silent error, while the move to promises will create an unhandled promise rejection if the caller did not plan for this.

This might be a good practice but should probably be documented.

What do you think?

**Comment by levynir** [comment]
> I am thinking that perhaps moving from callbacks promises produces unplanned site-effect of incompatible backward handling of errors. ...

My apologies, I re-checked the old code and the change *is* backwards compatible.

**Pull request merged**
