### PR TITLE
Use generic react native version to avoid duplicates

### PR DESCRIPTION
**Pull request by radko93**
Using a specified `react-native` version in `build.gradle` actually make gradle to include multiple versions.
image
image

### CODE REVIEW

**Comment by browniefed** [comment]
Thank you for this, been on vacation and get back in a few days. Will merge this then.

**Comment by browniefed** [comment]
Just pinging @seanadkinson on this. I assume this is an okay change, just would like someone else who understands gardle to have a look.

**Comment by radko93** [comment]
Any progress? It's not a big change :)

**Comment by browniefed** [comment]
Sorry about the delay, don't use this library so not too focused on it.

**Comment by browniefed** [comment]
v6.3.0 is out

**Pull request merged**
