### PR TITLE
Export the PushReceiver & Make sure calls are executed in order, no matter what screen they where called from

### PR DESCRIPTION
**Pull request by andreibarabas**
Background:

while you can definitely do

```
Intercom.registerIdentifiedUser({ userId: 'bob' })
.then(() => {	
	return Intercom.updateUser({		
 		email: 'email',		 		
 		name: 'name',
 	});
})
```

I found a huge problem when calling first (in app.js for example) Intercom.registerUnidentifiedUser, then log some events for the anonymous user (like See Welcome Screen) and then in login.js call the above functions to identify the user.

`E/Intercom: You cannot update the email of an anonymous user. Please call registerIdentified user instead. The email: _____ was NOT applied`

The solution is to use a promise chain inside the js client to make sure calls are executed in the right order (as intended by the dev).

It is also backward compatible, so you can use the promise chain call
```
Intercom.registerIdentifiedUser({ userId: 'bob' })
.then(() => {	
	return Intercom.updateUser({		
 		email: 'email',		 		
 		name: 'name',
 	});
})
```
but you can also use it without explicitly chaining the promises (thus resulting in a cleaner code)
```
Intercom.registerIdentifiedUser({ userId: 'bob' });
 Intercom.updateUser({		
 		email: 'email',		 		
 		name: 'name',
 	});
```

### CODE REVIEW

**Comment by browniefed** [comment]
Awesome! I'll get this merged and deployed tomorrow

**Comment by browniefed** [comment]
Sorry, was busy. Published as 6.1

**Comment by andreibarabas** [comment]
Sounds good @browniefed . Thanks

**Comment by ryankask** [comment]
Is this backwards incompatible? It looks like errors are swallowed in `_pushIntercomChain` (which also creates a resolved promise that isn't used).

I think the issues this is trying to solve should be handled by the application.

**Comment by andreibarabas** [comment]
@ryankask - the code is somewhat compatible, just the errors would only be logged, and not be caught in the catch.

Initially we've done it in our app, and it started to get ugly. Everything went ok with other libraries that use events, like mixpanel. 

It should be the purpose of the library to ensure the chain, but I agree that we could look for a better way for _pushIntercomChain not just to log the errors, but to throw them back. any ideas?

**Comment by ryankask** [comment]
I'm not sure if that's the library's job. I don't have any issues with this because I structure my code differently but using a global promise object seems a bit strange. It definitely shouldn't catch errors though.

I may not understand the pattern being used but you could implement it using a global promise in your app outside the client so other users don't have any issues.

**Comment by andreibarabas** [comment]
I'll think of another way to allow catching the errors, but it should be the libraries responsibility to make sure the calls are correctly called

**Pull request merged**
