### PR TITLE
Remove Intercom function that's no longer supported

### PR DESCRIPTION
**Pull request by adamrainsby**
Support for registerForRemoteNotifications was removed in the Intercom
iOS library 2.3.5 and later:

https://github.com/intercom/intercom-ios/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by atticoos** [comment]
+1, had to comment this out on my build due to full deprecation

**Comment by jtreanor** [comment]
Hi @adamrainsby and @ajwhite,

James here from the Intercom mobile team. This method was deprecated in version 2.1 (in March 2015) and finally removed in 2.3.5 as you have pointed out.

Let me know if you have any questions about Intercom for iOS :smile:

**Comment by atticoos** [comment]
Ty @jtreanor, let's :shipit: @asamiller

**Comment by kanerogers** [comment]
Ding ding, @asamiller ? :smile:

**Comment by browniefed** [comment]
I believe this was fixed in a different PR, if not feel free to rebase and let me know.

**Pull request closed without merging**
