### PR TITLE
Add logout method (reset does not log the user out)

### PR DESCRIPTION
**Pull request by evanjmg**
I've used reset and it's not logging my user out. It's simply hiding intercom. I'm no Objective C expert, feel free to add the objective C equivalent.

### CODE REVIEW

**Comment by evanjmg** [comment]
Intercom recommends using the logout method here: https://developers.intercom.com/docs/android-installation

**Review by albinekb — APPROVED** [review]

**Review by ohtangza — APPROVED** [review]

**Review by ohtangza — COMMENTED** [review]
I think the relevant documentation should be updated.

**Comment by peacechen** [comment]
The iOS side does call `logout()` in the `reset()` method.
https://github.com/tinycreative/react-native-intercom/blob/374faecd21ffc46d2582ea4d6e97b2ae3f8f0211/iOS/IntercomWrapper.m#L67

To remain consistent, the Android side should also call `logout` in the reset method.  Or remove logout from the iOS side, but that would involve more work adding the Objective-C method and JS hook.

Edit: just noticed that iOS calls `logout` but not `reset`.   Both iOS and Android should call both (first logout, then reset).

**Comment by jayporta** [comment]
reset() has been deprecated.

**Comment by browniefed** [comment]
Pretty sure I already merged this in a different PR

**Comment by albinekb** [comment]
Looks like https://github.com/tinycreative/react-native-intercom/pull/235

**Comment by jayporta** [comment]
You’re right. I downloaded the latest version and the logout function is
there. I was about to submit a PR myself. Thanks.

**Pull request closed without merging**
