### PR TITLE
Add GCM support, including compatibility with OneSignal

### PR DESCRIPTION
**Pull request by andreibarabas**

### CODE REVIEW

**Comment by browniefed** [comment]
Hey thank you for submitting this PR.

I'm going to ping @kuglemic and @seanadkinson and have them take a look and let me know as I'm not an active user of this package yet.

**Comment by seanadkinson** [comment]
Since this is opt-in functionality, I don't see any issue with it.  My only concern is SDK and build tools versions being upgraded.  @andreibarabas Is that going to cause issues when people upgrade?  I.E. will they need to bump their versions in their main application?  Or does it only matter that the `minSdkVersion` is still the same?  I'm not well versed in Android builds, so just trying to make sure this is a backwards compatible change.

**Comment by andreibarabas** [comment]
Hi @seanadkinson. To build the latest OneSignal SDK, I needed to upgrade the build tools, but there is no need for people to bump their versions of the main application as the minSdkVersion has not changed.

**Comment by seanadkinson** [comment]
Looks good to me then @browniefed 👍

**Comment by browniefed** [comment]
Sounds good, v5.9 published to NPM with these changes.

**Comment by thunghan** [comment]
Hi, what if we want FCM support instead of GCM?

**Comment by chendo** [comment]
The SDK bump in this PR is causing us issues as it doesn't appear we can use different `compileSdkVersion` between RN dependency versions. Has anyone solved this problem?

**Pull request merged**
