### PR TITLE
Bump Intercom to 5.5.1

### LINKED ISSUE #321: IOS - crashing on attach photo
Hey guys, how are you?

Just noticed that if I try to attach a photo on a conversation, my app suddenly crashes and I don't know what's going on.

```
2019-10-15 13:53:28.125793-0300 native[35506:918980] API error: <_UIKBCompatInputView: 0x7ffac5ca6ec0; frame = (0 0; 0 0); layer = <CALayer: 0x6000038db380>> returned 0 width, assuming UIViewNoIntrinsicMetric
2019-10-15 13:53:28.126124-0300 native[35506:918980] API error: <_UIKBCompatInputView: 0x7ffac5ca6ec0; frame = (0 0; 0 0); layer = <CALayer: 0x6000038db380>> returned 0 width, assuming UIViewNoIntrinsicMetric
2019-10-15 13:53:28.130129-0300 native[35506:918980] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600001a49360 'assistantHeight' TUISystemInputAssistantView:0x7ffac5dbda80.height == 45   (active)>",
    "<NSLayoutConstraint:0x600001a30dc0 'assistantView.bottom' TUISystemInputAssistantView:0x7ffac5dbda80.bottom == UIInputView:0x7ffac8010530.top   (active)>",
    "<NSLayoutConstraint:0x600001a30d70 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x7ffac820a040]-(0)-[TUISystemInputAssistantView:0x7ffac5dbda80]   (active)>",
    "<NSLayoutConstraint:0x600001a30690 'inputView.top' V:[_UIRemoteKeyboardPlaceholderView:0x7ffac820a040]-(0)-[UIInputView:0x7ffac8010530]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001a30d70 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x7ffac820a040]-(0)-[TUISystemInputAssistantView:0x7ffac5dbda80]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-10-15 13:53:28.608749-0300 native[35506:918980] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c3cb71 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23c47596 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.4 + 38
	4   CoreFoundation                      0x00007fff23c07f17 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 247
	5   CoreFoundation                      0x00007fff23ba609b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	6   native                              0x000000010efa8713 +[IntercomSDK_ITBBlockUtils imageBlockForUpload:appearance:] + 298
	7   native                              0x000000010f0d134e +[ICMConversationPart sendingPartWithBlocks:upload:] + 607
	8   native                              0x000000010f0b38e5 -[ICMConversationContentViewController replyToConversationWithBlocks:upload:] + 215
	9   native                              0x000000010f0b1975 -[ICMConversationContentViewController sendUpload:] + 177
	10  native                              0x000000010f08c36f -[ICMConversationViewController sendMessage:upload:] + 179
	11  native                              0x000000010f08be94 __74-[ICMConversationViewController inputAccessoryView:input:performedAction:]_block_invoke + 96
	12  libdispatch.dylib                   0x000000011201cdf8 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000011201dd6c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x000000011202be24 _dispatch_main_queue_callback_4CF + 1500
	15  CoreFoundation                      0x00007fff23b0ce49 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff23b07aa9 __CFRunLoopRun + 2329
	17  CoreFoundation                      0x00007fff23b06e66 CFRunLoopRunSpecific + 438
	18  GraphicsServices                    0x00007fff38346bb0 GSEventRunModal + 65
	19  UIKitCore                           0x00007fff47578dd0 UIApplicationMain + 1621
	20  native                              0x000000010e9c51f0 main + 112
	21  libdyld.dylib                       0x00007fff516ecd29 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

Any thoughts?

Thanks

### PR DESCRIPTION
**Pull request by felippepuhle**
Fixes https://github.com/tinycreative/react-native-intercom/issues/321

Giving the right/proper credits to @makirby that solved this

### CODE REVIEW

**Comment by sakarisson** [comment]
This is great. Are you going to release a new version with this change sometime in the near future?

**Comment by felippepuhle** [comment]
@Sakarisson you can add `pod 'Intercom', '~> 5.5.1'` to your `Podfile` for now, it solved for me (I'm still waiting for a release too)

**Comment by browniefed** [comment]
3.2 published

**Comment by smakosh** [comment]
The app is still crashing with the same error on iOS 13, RN 0.61.2

**Comment by felippepuhle** [comment]
@smakosh even on `13.2.0`?

**Comment by smakosh** [comment]
Yup

**Comment by felippepuhle** [comment]
Please provide more informations, I think you can use this issue (https://github.com/tinycreative/react-native-intercom/issues/321) or create a new one.

**Pull request merged**
