### PR TITLE
Upgrade to intercom v6

### PR DESCRIPTION
**Pull request by thevishnupradeep**
Necessary changes for v6.0 support

### CODE REVIEW

**Review by matiaspan — APPROVED** [review]

**Comment by pete183** [comment]
Please can I enquire when this will be merged?

**Comment by browniefed** [comment]
v15

**Comment by pete183** [comment]
@browniefed 
Amazing - have a great day!

**Comment by ramishaar** [comment]
hi @browniefed @thevishnupradeep ,

Do you know if we can expect an update to 6.1.0. This update is important for anyone using custom bots on intercom.

**Comment by browniefed** [comment]
Submit a PR @ramishaar and I'll release it.

**Comment by rolfb** [comment]
@browniefed Submitted #366, take a gander and release when ready :)

**Pull request merged**
