### PR TITLE
Fix unsubscribedFromEmails and Upgrade Intercom SDKs to 5.0.2

### PR DESCRIPTION
**Pull request by onlydave**

### CODE REVIEW

**Comment by onlydave** [comment]
Fixes #195

**Comment by idris** [comment]
@browniefed are you still maintaining this library?  It would be nice to see one of these v5 PRs merged.

If you're busy, I'd be happy to take ownership of the library and maintain it.

**Comment by browniefed** [comment]
@idris That would be great, I actually might be using this library shortly. 
But seriously if you would like to help out that would be great, I'd be happy to throw you on as a maintainer.

**Comment by browniefed** [comment]
Published with v11

**Comment by idris** [comment]
Sure, @browniefed we use this in production, so happy to be added as a maintainer and help out.

**Comment by browniefed** [comment]
@asamiller Hey can you add @idris as a maintainer of the project.

**Pull request merged**
